# Speech Enhancement
# ------------------------------------------------------------------------
bandlimiter:
    keys: ['lowpass', 'lowpass_ladder',
           'bandpass', 'bandpass_ladder',
           'highpass', 'highpass_ladder',
           'bandreject']
    weights: [1, 3, 
             1, 3,
             1, 3,
             3]

distortion:
    keys: ['distortion', 'hard_clipper', 'soft_clipper', 'bitcrush']
    weights: [2, 2, 2, 1]

compressor:
    keys: ['compressor', 'plosive', 'deesser', 'limiter']
    weights: [10, 10, 8, 10]

equalization:
    keys: ['parametric_eq', 'svf']
    weights: [5, 10]

reverb:
    keys: ['mono_reverb', 'rir_conv']
    weights: [8, 12]

delay:
    keys: ['delay']
    weights: [1]

micir_conv:
    keys: ['micir_conv']
    weights: [1]

add_noise:
    keys: ['add_noise']
    weights: [1]

modulation:
    keys: ['chorus', 'tremolo', 'flanger']
    weights: [1, 1, 1]

codec:
    keys: ['libmp3lame', 'aac', 'libvorbis', 'libopus']
    weights: [1, 1, 1, 1]

# General AFX Learning
# ------------------------------------------------------------------------
loudness_dynamics:
    keys: ['compressor', 'plosive', 'deesser', 'limiter',
           'noisegate', 'expander', 'tremolo']
    weights: [10, 10, 10, 10,
              10, 10, 10]


delay_and_reverb:
    keys: ['mono_reverb', 'delay'] # , 'pingpong_delay'
    weights: [10, 5] # , 5


stereo_image:
    keys: ['panning', 'imager']
    weights: [1, 1]

saturation:
    keys: ['soft_clipper']
    weights: [1]

limiter:
    keys: ['limiter']
    weights: [1]

rir_conv:
    keys: ['rir_conv']
    weights: [1]
