damping: damp
room_size: room
wet_level: wet
dry_level: dry
out_low: low
out_high: high
threshold_db: thres
attack_ms: att
release_ms: rel
frequency_hz: freq
lfo_frequency_hz: freq
delay_seconds: delay
centre_frequency_hz: freq
gain_db: gain
centre_delay_ms: delay
lowpass_ladder: lpf_ladder
highpass_ladder: hpf_ladder
bandpass_ladder: bpf_ladder
hardness: hard
asymmetry: asym
bit_depth: bit
modulation: mod
feedback_gain_db: feedback
mono_reverb: mono_rev
noise: noise
knee_db: knee
phase_delta: delta
lr_ratio: ratio
lowpass_butter: lpf_butter
bandpass_butter: bpf_butter
highpass_butter: hpf_butter
inverted_compressor: invert_comp
spectral_convolve: spec_conv

#sidechain: side
